language: python
cache: pip

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - sci_py_import_all
  - python setup.py test
  - sci_py_test_style .
